version: '3'

services:
  app:
    image: mtga_limited:latest
    ports:
     - "${MTGA_LIMITED_PORT}:${MTGA_LIMITED_PORT}"
    environment:
     - ./.env
    command: "uvicorn main:app --reload --host 0.0.0.0 --port ${MTGA_LIMITED_PORT}"

